mqttBroker:
  host: node2.emqx.stockup.site
  port: 1883
  username: "testuser"
  password: "testpassword"
  clientId: "clientId1"
plugins:
  dir: ../detecc-core/compiled/server
database:
  database: "detecctor"
  host: "77.53.193.19"
  username: "admin"
  password: "T4UGkd%5Ez%26rzw"
  port: 27017
